### ISSUE TITLE
Medial Ha is not converted

### ISSUE THREAD

**Issue by sanlinnaing** [trhura/paytan#6]
There is an error when convert <i>Zawgyi encoded text</i> to <i>Unicode encoded text</i> in <strong><i>Medial Ha </i></strong>such as "မှ".
Convert following text as a input <strong>"မိန္းမမွာမီး ေယာက်ာ္းမွာဆီး".</strong>

**Comment by trhura** [comment]
It may take a while for me to verify and fix this issue. If you are feeling adventerous, why don't you play around a bit with the rules file to fix the issue.

Check out the zg2uni rules file, which contains the regex search and replace fields separated by `|`.
https://github.com/trhura/paytan/blob/master/converter/zg12uni51.rules

Line 10 looks suspicious since it is replacing `[@{ha}@{ha_short}]` with `@{wa}`.

**Comment by yelinaung** [comment]
Related to yelinaung/mmfont#1
